name: Azure App Service - Build and Deploy (React build/)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x' # Match your App Service "Runtime Stack" (Node - 20-lts)

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build React app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to Azure App Service (serve build/)
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      # IMPORTANT:
      # 1) In your App Service (Linux) Configuration:
      #    - Application setting: WEBSITES_PORT = 8080
      #    - Startup Command: npx serve -s build -l 8080
      # 2) Add secret AZUREAPPSERVICE_PUBLISHPROFILE in the repo with your publish profile XML.
      # 3) Set the app-name below to your App Service name exactly as in Azure Portal.

      - name: Deploy build/ to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: brodbutiken-webapp # TODO: confirm this matches your App Service Name exactly
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./build